"""Migrations reais: reversíveis e fiéis às invariantes do schema."""

import pytest
from alembic import command
from conftest import alembic_config, conexao
from sqlalchemy import text
from sqlalchemy.exc import IntegrityError

SCHEMAS_DO_PRODUTO = ("meta", "raw", "curated", "quality")


def tabelas_do_produto(settings) -> set[str]:
    with conexao(settings) as con:
        linhas = con.execute(
            text(
                "select table_schema || '.' || table_name from information_schema.tables "
                "where table_schema = any(:schemas)"
            ),
            {"schemas": list(SCHEMAS_DO_PRODUTO)},
        )
        return {linha[0] for linha in linhas}


def schemas_existentes(settings) -> set[str]:
    with conexao(settings) as con:
        linhas = con.execute(text("select schema_name from information_schema.schemata"))
        return {linha[0] for linha in linhas}


def test_upgrade_downgrade_upgrade_volta_ao_mesmo_schema(banco_limpo):
    config = alembic_config(banco_limpo)

    command.upgrade(config, "head")
    depois_do_upgrade = tabelas_do_produto(banco_limpo)
    assert "meta.dataset_version" in depois_do_upgrade
    # As 13 tabelas do dataset entregue pelos organizadores (inventário S3 de 28/09/2026).
    assert len({t for t in depois_do_upgrade if t.startswith("raw.")}) == 13

    command.downgrade(config, "base")
    assert tabelas_do_produto(banco_limpo) == set()
    assert schemas_existentes(banco_limpo).isdisjoint(SCHEMAS_DO_PRODUTO)

    command.upgrade(config, "head")
    assert tabelas_do_produto(banco_limpo) == depois_do_upgrade


def test_dataset_version_aceita_uma_unica_linha(banco_migrado):
    inserir = text(
        "insert into meta.dataset_version (id, version, source) values (:id, :v, 'fixture')"
    )
    with conexao(banco_migrado) as con:
        con.execute(inserir, {"id": 1, "v": "v1"})
    with pytest.raises(IntegrityError), conexao(banco_migrado) as con:
        con.execute(inserir, {"id": 2, "v": "v2"})


def test_modelos_coincidem_com_as_migrations(banco_migrado):
    # Levanta AutogenerateDiffsDetected se um modelo e o schema migrado divergirem.
    command.check(alembic_config(banco_migrado))
