"""Migrations reais: reversíveis e fiéis às invariantes do schema."""

import pytest
from alembic import command
from conftest import alembic_config, conexao
from sqlalchemy import text
from sqlalchemy.exc import IntegrityError

SCHEMAS_DO_PRODUTO = ("meta", "raw", "curated", "quality", "app")


def tabelas_do_produto(settings) -> set[str]:
    with conexao(settings) as con:
        linhas = con.execute(
            text(
                "select table_schema || '.' || table_name from information_schema.tables "
                "where table_schema = any(:schemas)"
            ),
            {"schemas": list(SCHEMAS_DO_PRODUTO)},
        )
        return {linha[0] for linha in linhas}


def schemas_existentes(settings) -> set[str]:
    with conexao(settings) as con:
        linhas = con.execute(text("select schema_name from information_schema.schemata"))
        return {linha[0] for linha in linhas}


def test_upgrade_downgrade_upgrade_volta_ao_mesmo_schema(banco_limpo):
    config = alembic_config(banco_limpo)

    command.upgrade(config, "head")
    depois_do_upgrade = tabelas_do_produto(banco_limpo)
    assert "meta.dataset_version" in depois_do_upgrade
    # As 13 tabelas do dataset entregue pelos organizadores (inventário S3 de 28/09/2026).
    assert len({t for t in depois_do_upgrade if t.startswith("raw.")}) == 13

    command.downgrade(config, "base")
    assert tabelas_do_produto(banco_limpo) == set()
    assert schemas_existentes(banco_limpo).isdisjoint(SCHEMAS_DO_PRODUTO)

    command.upgrade(config, "head")
    assert tabelas_do_produto(banco_limpo) == depois_do_upgrade


def test_dataset_version_aceita_uma_unica_linha(banco_migrado):
    inserir = text(
        "insert into meta.dataset_version (id, version, source) values (:id, :v, 'fixture')"
    )
    with conexao(banco_migrado) as con:
        con.execute(inserir, {"id": 1, "v": "v1"})
    with pytest.raises(IntegrityError), conexao(banco_migrado) as con:
        con.execute(inserir, {"id": 2, "v": "v2"})


def test_modelos_coincidem_com_as_migrations(banco_migrado):
    # Levanta AutogenerateDiffsDetected se um modelo e o schema migrado divergirem.
    command.check(alembic_config(banco_migrado))


def test_sessao_so_aceita_dispositivo_conhecido(banco_migrado):
    inserir = text(
        "insert into app.sessoes (token_hash, customer_id, expira_em, dispositivo)"
        " values (:h, 'CLI-A', now(), :d)"
    )
    with conexao(banco_migrado) as con:
        con.execute(inserir, {"h": "h1", "d": "cadastrado"})
    with pytest.raises(IntegrityError), conexao(banco_migrado) as con:
        con.execute(inserir, {"h": "h2", "d": "confiavel"})


BLOQUEIO = text(
    "insert into app.bloqueios (id, customer_id, product_id, produto, tipo, motivo, dispositivo,"
    " reversivel_ate, desfeito_em, desfeito_por)"
    " values (:id, 'CLI-A', 'CRT-1', 'Tarjeta Crédito', :tipo, :motivo, :dispositivo,"
    " now() + interval '7 days', :desfeito_em, :desfeito_por)"
)
VALIDO = {"tipo": "completo", "motivo": "pedido", "dispositivo": "cadastrado",
          "desfeito_em": None, "desfeito_por": None}  # fmt: skip


def test_um_bloqueio_ativo_por_cartao_do_cliente(banco_migrado):
    with conexao(banco_migrado) as con:
        con.execute(BLOQUEIO, {**VALIDO, "id": "BL-1"})
    with pytest.raises(IntegrityError), conexao(banco_migrado) as con:
        con.execute(BLOQUEIO, {**VALIDO, "id": "BL-2"})
    with conexao(banco_migrado) as con:
        con.execute(text("update app.bloqueios set desfeito_em = now(), desfeito_por = 'cliente'"))
        con.execute(BLOQUEIO, {**VALIDO, "id": "BL-3"})


@pytest.mark.parametrize(
    "invalido",
    [
        {"tipo": "total"},
        {"motivo": "outro"},
        {"dispositivo": "confiavel"},
        {"desfeito_em": "2026-09-30", "desfeito_por": "robo"},
        {"desfeito_em": "2026-09-30"},  # desfeito sem dizer por quem
        {"desfeito_por": "atendente"},  # quem desfez sem dizer quando
    ],
)
def test_bloqueio_so_aceita_valores_conhecidos_e_desfeito_completo(banco_migrado, invalido):
    with pytest.raises(IntegrityError), conexao(banco_migrado) as con:
        con.execute(BLOQUEIO, {**VALIDO, "id": "BL-1", **invalido})
